### ISSUE TITLE
Different locales support

### ISSUE THREAD

**Issue by WhereIsLucas** [spatie/laravel-dashboard-belgian-trains-tile#2]
Hi fellow belgians,

I'm interested in getting this to work with other locales supported by iRail.
I'm willing to develop it, and do a pull request.

Would you merge such a pull request?

Thanks for your answer!

**Comment by freekmurze** [comment]
We probably would if the code is simple.

And should we didn't be interested in maintaining it, you could put your work in a repo of your own, and we'd happily link to it from our docs. 👍
